Repository OCA/rma, pull requests merged in 2020-11, with the labels that each got.

#177 [13.0][MIG] rma: Migration to 13.0
  rma/README.rst
  rma/__init__.py
  rma/__manifest__.py
  rma/controllers/__init__.py
  rma/controllers/main.py
  rma/data/mail_data.xml
  rma/data/rma_operation_data.xml
  rma/data/stock_data.xml
  rma/hooks.py
  rma/i18n/es.po
  rma/i18n/pt_BR.po
  rma/i18n/rma.pot
  rma/models/__init__.py
  rma/models/account_move.py
  rma/models/res_company.py
  rma/models/res_partner.py
  rma/models/res_users.py
  rma/models/rma.py
  rma/models/rma_operation.py
  rma/models/rma_team.py
  rma/models/stock_move.py
  rma/models/stock_picking.py
  rma/models/stock_warehouse.py
  rma/readme/CONFIGURE.rst
  rma/readme/CONTRIBUTORS.rst
  rma/readme/DESCRIPTION.rst
  rma/readme/ROADMAP.rst
  rma/readme/USAGE.rst
  rma/report/report.xml
  rma/security/ir.model.access.csv
  rma/security/rma_security.xml
  rma/static/description/icon.png
  rma/static/description/index.html
  rma/tests/__init__.py
  rma/tests/test_rma.py
  rma/views/menus.xml
  rma/views/report_rma.xml
  rma/views/res_partner_views.xml
  rma/views/rma_portal_templates.xml
  rma/views/rma_team_views.xml
  rma/views/rma_views.xml
  rma/views/stock_picking_views.xml
  rma/views/stock_warehouse_views.xml
  rma/wizard/__init__.py
  rma/wizard/rma_delivery.py
  rma/wizard/rma_delivery_views.xml
  rma/wizard/rma_split.py
  rma/wizard/rma_split_views.xml
  rma/wizard/stock_picking_return.py
  rma/wizard/stock_picking_return_views.xml
  setup/.setuptools-odoo-make-default-ignore
  setup/README
  setup/rma/odoo/addons/rma
  setup/rma/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#179 [12.0][FIX] rma: RMA quantities are not quantities on hand
  rma/__manifest__.py
  rma/data/stock_data.xml
  rma/hooks.py
  rma/models/stock_warehouse.py
  rma/tests/test_rma.py
Labels: approved, bot is merging ⏳

#178 [13.0][MIG] rma_sale: Migration to 13.0
  rma_sale/README.rst
  rma_sale/__init__.py
  rma_sale/__manifest__.py
  rma_sale/controllers/__init__.py
  rma_sale/controllers/rma_portal.py
  rma_sale/controllers/sale_portal.py
  rma_sale/i18n/es.po
  rma_sale/i18n/pt_BR.po
  rma_sale/i18n/rma_sale.pot
  rma_sale/models/__init__.py
  rma_sale/models/rma.py
  rma_sale/models/sale.py
  rma_sale/models/stock_move.py
  rma_sale/readme/CONTRIBUTORS.rst
  rma_sale/readme/DESCRIPTION.rst
  rma_sale/readme/ROADMAP.rst
  rma_sale/readme/USAGE.rst
  rma_sale/static/description/icon.png
  rma_sale/static/description/index.html
  rma_sale/static/src/scss/rma_sale.scss
  rma_sale/tests/__init__.py
  rma_sale/tests/test_rma_sale.py
  rma_sale/views/assets.xml
  rma_sale/views/report_rma.xml
  rma_sale/views/rma_views.xml
  rma_sale/views/sale_portal_template.xml
  rma_sale/views/sale_views.xml
  rma_sale/wizard/__init__.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
  setup/rma_sale/odoo/addons/rma_sale
  setup/rma_sale/setup.py
Labels: approved, bot is merging ⏳

#181 [IMP] rma, rma_sale: shipping address
  rma/README.rst
  rma/__manifest__.py
  rma/migrations/12.0.2.0.0/post-migration.py
  rma/models/rma.py
  rma/models/stock_move.py
  rma/static/description/index.html
  rma/tests/test_rma.py
  rma/views/rma_views.xml
  rma_sale/controllers/sale_portal.py
  rma_sale/views/sale_portal_template.xml
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
Labels: approved, bot is merging ⏳, enhancement, needs review

#182 [IMP] rma_sale: shipping address portal default
  rma/views/report_rma.xml
  rma_sale/views/sale_portal_template.xml
Labels: approved, bot is merging ⏳
