Repository OCA/rma, pull requests merged in 2020-10, with the labels that each got.

#164 [ADD] website_rma: new module
  website_rma/__init__.py
  website_rma/__manifest__.py
  website_rma/controllers/__init__.py
  website_rma/controllers/main.py
  website_rma/data/ir_model_data.xml
  website_rma/data/website_data.xml
  website_rma/i18n/es.po
  website_rma/i18n/website_rma.pot
  website_rma/models/__init__.py
  website_rma/models/ir_model.py
  website_rma/readme/CONTRIBUTORS.rst
  website_rma/readme/README.rst
  website_rma/readme/USAGE.rst
  website_rma/static/src/js/website_rma.js
  website_rma/static/src/js/website_rma.tour.js
  website_rma/tests/__init__.py
  website_rma/tests/test_website_rma.py
  website_rma/views/assets.xml
  website_rma/views/request_rma_form.xml
  website_rma/views/website_rma_portal_templates.xml
  website_rma/views/website_templates.xml
Labels: bot is merging ⏳, needs review

#168 [FIX+IMP] rma: usability
  rma/migrations/12.0.2.0.0/post-migration.py
  rma/models/rma.py
  rma/views/report_rma.xml
  rma/views/rma_portal_templates.xml
  rma/views/rma_views.xml
  rma_sale/views/sale_views.xml
Labels: approved, bot is merging ⏳

#171 [FIX] rma: return permissions
  rma/models/rma.py
Labels: approved, bot is merging ⏳

#172 [FIX] rma: multicompany returns
  rma/models/rma.py
Labels: approved, bot is merging ⏳

#173 [FIX] rma: non rma users confirm
  rma/models/stock_move.py
Labels: approved, bot is merging ⏳

#174 [FIX] rma: pass company as record to procurement
  rma/models/rma.py
Labels: approved, bot is merging ⏳

#175 [12.0][FIX] rma_sale: show related RMAs without default filters
  rma_sale/models/sale.py
Labels: bot is merging ⏳

#176 [FIX] rma: internal users portal
  rma/controllers/main.py
  rma/views/rma_portal_templates.xml
Labels: bot is merging ⏳
