Repository OCA/rma, pull requests merged in 2021-04, with the labels that each got.

#213 [IMP][FIX] Forward ports from v12.0
  rma/__manifest__.py
  rma/data/mail_data.xml
  rma/models/__init__.py
  rma/models/account_move.py
  rma/models/res_company.py
  rma/models/res_config_settings.py
  rma/models/rma.py
  rma/models/stock_move.py
  rma/tests/test_rma.py
  rma/views/res_config_settings_views.xml
  rma/views/rma_portal_templates.xml
  rma/views/rma_views.xml
  rma_sale/controllers/sale_portal.py
  rma_sale/models/rma.py
  rma_sale/models/sale.py
  rma_sale/static/src/js/rma_portal_form.js
  rma_sale/views/assets.xml
  rma_sale/views/sale_portal_template.xml
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
Labels: approved, bot is merging ⏳

#212 [FIX] rma_sale: fix wrong values for RMA creation
  rma_sale/controllers/sale_portal.py
  rma_sale/wizard/sale_order_rma_wizard.py
Labels: bot is merging ⏳

#214 [FIX] rma_sale_mrp: infinite loop
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#217 [FIX] website_rma: controller implementation
  website_rma/controllers/main.py
Labels: bot is merging ⏳

#218 [FIX] website_rma: wrong readme parts
  website_rma/README.rst
  website_rma/readme/DESCRIPTION.rst
  website_rma/static/description/index.html
Labels: approved, bot is merging ⏳

#216 [FIX] rma_sale_mrp: handle exceptions when qty is forced
  rma_sale/models/sale.py
  rma_sale/tests/test_rma_sale.py
  rma_sale_mrp/tests/test_rma_sale_mrp.py
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
Labels: approved, bot is merging ⏳, ready to merge

#219 [FW][FIX] rma_sale: recurrent RMA
  rma_sale/models/sale.py
  rma_sale/tests/test_rma_sale.py
Labels: approved, bot is merging ⏳
