Repository OCA/rma, pull requests merged in 2021-03, with the labels that each got.

#183 [ADD] rma_sale_mrp: allow returning phantom products
  rma/models/account_invoice.py
  rma/models/rma.py
  rma/views/rma_portal_templates.xml
  rma/views/rma_views.xml
  rma_sale/controllers/sale_portal.py
  rma_sale/models/rma.py
  rma_sale/models/sale.py
  rma_sale/views/sale_portal_template.xml
  rma_sale/wizard/sale_order_rma_wizard_views.xml
  rma_sale_mrp/README.rst
  rma_sale_mrp/__init__.py
  rma_sale_mrp/__manifest__.py
  rma_sale_mrp/i18n/es.po
  rma_sale_mrp/i18n/rma_sale_mrp.pot
  rma_sale_mrp/models/__init__.py
  rma_sale_mrp/models/account_invoice.py
  rma_sale_mrp/models/rma.py
  rma_sale_mrp/models/sale_order.py
  rma_sale_mrp/readme/CONTRIBUTORS.rst
  rma_sale_mrp/readme/DESCRIPTION.rst
  rma_sale_mrp/readme/ROADMAP.rst
  rma_sale_mrp/readme/USAGE.rst
  rma_sale_mrp/static/description/index.html
  rma_sale_mrp/tests/__init__.py
  rma_sale_mrp/tests/test_rma_sale_mrp.py
  rma_sale_mrp/views/report_rma.xml
  rma_sale_mrp/views/rma_views.xml
  rma_sale_mrp/views/sale_order_portal_template.xml
  rma_sale_mrp/wizard/__init__.py
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
  rma_sale_mrp/wizard/sale_order_rma_wizard_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#206 [IMP] rma_sale: portal ux
  rma_sale/static/src/js/rma_portal_form.js
  rma_sale/views/assets.xml
  rma_sale/views/sale_portal_template.xml
Labels: approved, bot is merging ⏳

#207 [12.0][FIX] rma: Set default source location for RMA created from scratch
  rma/models/rma.py
Labels: approved, bot is merging ⏳, enhancement, needs review

#205 [IMP] rma: automatic notification subtypes
  rma/data/mail_data.xml
  rma/models/rma.py
  rma/tests/test_rma.py
Labels: approved, bot is merging ⏳, ready to merge
