Repository OCA/rma, pull requests merged in 2022-09, with the labels that each got.

#302 [14.0][DCK] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: bot is merging ⏳

#301 [14.0][IMP] rma: Use _prepare_home_portal_values() function.
  rma/controllers/main.py
  rma/views/rma_portal_templates.xml
Labels: approved, bot is merging ⏳

#303 [15.0][IMP] rma: Use _prepare_home_portal_values() function.
  rma/controllers/main.py
  rma/views/rma_portal_templates.xml
Labels: approved, bot is merging ⏳

#305 [14.0][FIX] rma
  rma/models/rma.py
Labels: approved, bot is merging ⏳

#276 [14.0][MIG] rma_sale_mrp: Migration to 14.0
  rma_sale_mrp/README.rst
  rma_sale_mrp/__init__.py
  rma_sale_mrp/__manifest__.py
  rma_sale_mrp/i18n/es.po
  rma_sale_mrp/i18n/pt.po
  rma_sale_mrp/i18n/pt_BR.po
  rma_sale_mrp/i18n/rma_sale_mrp.pot
  rma_sale_mrp/models/__init__.py
  rma_sale_mrp/models/account_move.py
  rma_sale_mrp/models/rma.py
  rma_sale_mrp/models/sale_order.py
  rma_sale_mrp/readme/CONTRIBUTORS.rst
  rma_sale_mrp/readme/DESCRIPTION.rst
  rma_sale_mrp/readme/ROADMAP.rst
  rma_sale_mrp/readme/USAGE.rst
  rma_sale_mrp/security/ir.model.access.csv
  rma_sale_mrp/static/description/icon.png
  rma_sale_mrp/static/description/index.html
  rma_sale_mrp/tests/__init__.py
  rma_sale_mrp/tests/test_rma_sale_mrp.py
  rma_sale_mrp/views/report_rma.xml
  rma_sale_mrp/views/rma_views.xml
  rma_sale_mrp/views/sale_order_portal_template.xml
  rma_sale_mrp/wizard/__init__.py
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
  rma_sale_mrp/wizard/sale_order_rma_wizard_views.xml
  setup/rma_sale_mrp/odoo/addons/rma_sale_mrp
  setup/rma_sale_mrp/setup.py
Labels: bot is merging ⏳, stale

#306 [14.0][FIX] rma (Action v14 compatibility)
  rma/models/rma.py
  rma/models/stock_picking.py
Labels: bot is merging ⏳

#308 [14.0][FIX] rma (Make additional actions 14.0 compatible)
  rma/models/rma.py
Labels: bot is merging ⏳

#311 [13.0][DCK] Updated from template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: bot is merging ⏳

#310 [13.0][FIX] rma_sale: Misc changes
  rma_sale/models/rma.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
Labels: approved, bot is merging ⏳

#312 [14.0][FIX] rma_sale: Misc changes
  rma_sale/models/rma.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
Labels: bot is merging ⏳
