Repository OCA/rma, pull requests merged in 2022-02, with the labels that each got.

#256 [14.0] rma: forward ports from 13.0
  rma/README.rst
  rma/__manifest__.py
  rma/hooks.py
  rma/i18n/es.po
  rma/i18n/rma.pot
  rma/models/__init__.py
  rma/models/res_config_settings.py
  rma/models/rma.py
  rma/models/rma_finalization.py
  rma/readme/CONFIGURE.rst
  rma/readme/USAGE.rst
  rma/security/ir.model.access.csv
  rma/security/rma_security.xml
  rma/static/description/index.html
  rma/tests/test_rma.py
  rma/views/report_rma.xml
  rma/views/res_config_settings_views.xml
  rma/views/rma_finalization_views.xml
  rma/views/rma_portal_templates.xml
  rma/views/rma_views.xml
  rma/wizard/__init__.py
  rma/wizard/rma_finalization_wizard.py
  rma/wizard/rma_finalization_wizard_views.xml
Labels: bot is merging ⏳

#259 [FIX] rma_sale_mrp: description
  rma_sale_mrp/views/sale_order_portal_template.xml
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
Labels: approved, bot is merging ⏳

#260 [FIX] rma_sale_mrp: description
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
Labels: bot is merging ⏳

#252 [IMP] rma_sale: avoid submit form in portal if no info
  rma_sale/static/src/js/rma_portal_form.js
Labels: approved, bot is merging ⏳

#261 [FIX] rma: refund permissions
  rma/models/rma.py
  rma/security/ir.model.access.csv
  rma/security/rma_security.xml
  rma/tests/test_rma.py
Labels: approved, bot is merging ⏳

#120 crm_claim_rma: use procurement for delivery
  crm_claim_rma/models/__init__.py
  crm_claim_rma/models/crm_claim.py
  crm_claim_rma/models/procurement_group.py
  crm_claim_rma/security/ir.model.access.csv
  crm_claim_rma/tests/test_picking_creation.py
  crm_claim_rma/views/crm_claim.xml
  crm_claim_rma/wizards/claim_make_picking.py
  crm_claim_rma/wizards/claim_make_picking.xml
  crm_rma_stock_location/tests/test_make_picking_from_picking.py
  crm_rma_stock_location/wizards/claim_make_picking.py
Labels: enhancement, needs review, bot is merging ⏳, stale
