Repository OCA/rma, pull requests merged in 2022-07, with the labels that each got.

#275 [13.0][FIX] rma + rma_sale: Allow to create an RMA to a user with access_token to sale order (no user created).
  rma/models/rma.py
  rma_sale/controllers/sale_portal.py
  rma_sale/views/sale_portal_template.xml
  rma_sale/wizard/sale_order_rma_wizard.py
Labels: approved, bot is merging ⏳

#284 [14.0][FIX] rma + rma_sale: Allow to create an RMA to a user with access_token to sale order (no user created)
  rma/models/rma.py
  rma_sale/controllers/sale_portal.py
  rma_sale/views/sale_portal_template.xml
  rma_sale/wizard/sale_order_rma_wizard.py
Labels: bot is merging ⏳

#286 [15.0][MIG] stock_production_lot_warranty
  setup/stock_production_lot_warranty/odoo/addons/stock_production_lot_warranty
  setup/stock_production_lot_warranty/setup.py
  stock_production_lot_warranty/README.rst
  stock_production_lot_warranty/__init__.py
  stock_production_lot_warranty/__manifest__.py
  stock_production_lot_warranty/i18n/pt.po
  stock_production_lot_warranty/i18n/pt_BR.po
  stock_production_lot_warranty/i18n/stock_production_lot_warranty.pot
  stock_production_lot_warranty/models/__init__.py
  stock_production_lot_warranty/models/stock_production_lot.py
  stock_production_lot_warranty/readme/CONFIGURE.rst
  stock_production_lot_warranty/readme/CONTRIBUTORS.rst
  stock_production_lot_warranty/readme/CREDITS.rst
  stock_production_lot_warranty/readme/DESCRIPTION.rst
  stock_production_lot_warranty/readme/USAGE.rst
  stock_production_lot_warranty/static/description/icon.png
  stock_production_lot_warranty/static/description/index.html
  stock_production_lot_warranty/tests/__init__.py
  stock_production_lot_warranty/tests/test_product_lot_warranty.py
  stock_production_lot_warranty/views/stock_production_lot.xml
Labels: approved, migration, bot is merging ⏳
