Repository OCA/rma, pull requests merged in 2023-09, with the labels that each got.

#364 [16.0][MIG] rma_sale: Migration to 16.0
  rma_sale/README.rst
  rma_sale/__init__.py
  rma_sale/__manifest__.py
  rma_sale/controllers/__init__.py
  rma_sale/controllers/rma_portal.py
  rma_sale/controllers/sale_portal.py
  rma_sale/i18n/de.po
  rma_sale/i18n/es.po
  rma_sale/i18n/it.po
  rma_sale/i18n/nl.po
  rma_sale/i18n/pt.po
  rma_sale/i18n/pt_BR.po
  rma_sale/i18n/rma_sale.pot
  rma_sale/i18n/ro.po
  rma_sale/models/__init__.py
  rma_sale/models/account_move.py
  rma_sale/models/res_company.py
  rma_sale/models/res_config_settings.py
  rma_sale/models/rma.py
  rma_sale/models/sale.py
  rma_sale/models/stock_move.py
  rma_sale/readme/CONTRIBUTORS.rst
  rma_sale/readme/DESCRIPTION.rst
  rma_sale/readme/ROADMAP.rst
  rma_sale/readme/USAGE.rst
  rma_sale/security/ir.model.access.csv
  rma_sale/static/description/icon.png
  rma_sale/static/description/index.html
  rma_sale/static/src/js/rma_portal_form.js
  rma_sale/static/src/scss/rma_sale.scss
  rma_sale/static/src/tests/test_rma_sale_portal_tour.esm.js
  rma_sale/tests/__init__.py
  rma_sale/tests/test_rma_sale.py
  rma_sale/tests/test_rma_sale_portal.py
  rma_sale/views/account_move_views.xml
  rma_sale/views/report_rma.xml
  rma_sale/views/res_config_settings_views.xml
  rma_sale/views/rma_views.xml
  rma_sale/views/sale_portal_template.xml
  rma_sale/views/sale_views.xml
  rma_sale/wizard/__init__.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
  setup/rma_sale/odoo/addons/rma_sale
  setup/rma_sale/setup.py
Labels: approved, bot is merging ⏳

#366 [16.0][FIX] rma: _get_sequence_values signature
  rma/models/stock_warehouse.py
Labels: bot is merging ⏳

#365 [16.0][MIG] rma_sale_mrp: Migration to version 16.0
  rma_sale_mrp/README.rst
  rma_sale_mrp/__init__.py
  rma_sale_mrp/__manifest__.py
  rma_sale_mrp/i18n/es.po
  rma_sale_mrp/i18n/pt.po
  rma_sale_mrp/i18n/pt_BR.po
  rma_sale_mrp/i18n/rma_sale_mrp.pot
  rma_sale_mrp/models/__init__.py
  rma_sale_mrp/models/account_move.py
  rma_sale_mrp/models/rma.py
  rma_sale_mrp/models/sale_order.py
  rma_sale_mrp/readme/CONTRIBUTORS.rst
  rma_sale_mrp/readme/DESCRIPTION.rst
  rma_sale_mrp/readme/ROADMAP.rst
  rma_sale_mrp/readme/USAGE.rst
  rma_sale_mrp/security/ir.model.access.csv
  rma_sale_mrp/static/description/icon.png
  rma_sale_mrp/static/description/index.html
  rma_sale_mrp/tests/__init__.py
  rma_sale_mrp/tests/test_rma_sale_mrp.py
  rma_sale_mrp/views/report_rma.xml
  rma_sale_mrp/views/rma_views.xml
  rma_sale_mrp/views/sale_order_portal_template.xml
  rma_sale_mrp/wizard/__init__.py
  rma_sale_mrp/wizard/sale_order_rma_wizard.py
  rma_sale_mrp/wizard/sale_order_rma_wizard_views.xml
  setup/rma_sale_mrp/odoo/addons/rma_sale_mrp
  setup/rma_sale_mrp/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#368 [15.0][FIX] rma_sale_mrp: sale wizard line edition
  rma_sale_mrp/wizard/sale_order_rma_wizard_views.xml
Labels: approved, bot is merging ⏳

#369 [16.0][FIX] rma_sale_mrp: sale wizard line edition
  rma_sale_mrp/wizard/sale_order_rma_wizard_views.xml
Labels: bot is merging ⏳
