Repository OCA/rma, pull requests merged in 2024-06, with the labels that each got.

#394 [17.0][MIG] product_warranty: Migration to 17.0
  product_warranty/README.rst
  product_warranty/__init__.py
  product_warranty/__manifest__.py
  product_warranty/demo/product_warranty.xml
  product_warranty/demo/res_company.xml
  product_warranty/i18n/es.po
  product_warranty/i18n/es_MX.po
  product_warranty/i18n/es_PA.po
  product_warranty/i18n/es_VE.po
  product_warranty/i18n/fr.po
  product_warranty/i18n/it.po
  product_warranty/i18n/nl.po
  product_warranty/i18n/product_warranty.pot
  product_warranty/i18n/pt_BR.po
  product_warranty/i18n/ro.po
  product_warranty/images/product_warranty.png
  product_warranty/models/__init__.py
  product_warranty/models/product_supplierinfo.py
  product_warranty/models/product_template.py
  product_warranty/models/res_company.py
  product_warranty/models/return_instruction.py
  product_warranty/pyproject.toml
  product_warranty/readme/CONFIGURE.md
  product_warranty/readme/CONTRIBUTORS.md
  product_warranty/readme/CREDITS.md
  product_warranty/readme/DESCRIPTION.md
  product_warranty/readme/USAGE.md
  product_warranty/security/ir.model.access.csv
  product_warranty/static/description/icon.png
  product_warranty/static/description/index.html
  product_warranty/tests/__init__.py
  product_warranty/tests/test_product_warranty.py
  product_warranty/views/product_supplierinfo_views.xml
  product_warranty/views/product_template_views.xml
  product_warranty/views/res_company_views.xml
  product_warranty/views/return_instructions_views.xml
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#392 [16.0][IMP] RMA - refactor to use procurement run
  rma/README.rst
  rma/__manifest__.py
  rma/hooks.py
  rma/migrations/16.0.1.4.0/post-migration.py
  rma/models/rma.py
  rma/models/stock_move.py
  rma/models/stock_picking.py
  rma/models/stock_warehouse.py
  rma/readme/CONTRIBUTORS.rst
  rma/readme/ROADMAP.rst
  rma/static/description/index.html
  rma/tests/test_rma.py
  rma/wizard/stock_picking_return.py
  rma_sale/models/__init__.py
  rma_sale/models/rma.py
  rma_sale/models/sale.py
  rma_sale/models/stock_move.py
  rma_sale/wizard/__init__.py
  rma_sale/wizard/stock_picking_return.py
Labels: approved, ready to merge, bot is merging ⏳

#396 [16.0][OU-FIX] rma: Improve migration script to create picking types (only if not set)
  rma/migrations/16.0.1.4.0/post-migration.py
  rma/models/stock_warehouse.py
  rma/tests/test_rma.py
Labels: bot is merging ⏳

#399 [15.0][FIX] rma: Make the quantity comparison correctly (with precision_digits)
  rma/README.rst
  rma/__manifest__.py
  rma/models/stock_move.py
  rma/static/description/index.html
Labels: approved, bot is merging ⏳

#400 [16.0][FIX] rma: Make the quantity comparison correctly (with precision_digits)
  rma/models/stock_move.py
  rma/models/stock_picking.py
Labels: approved, bot is merging ⏳

#401 [17.0][FIX] rma: Make the quantity comparison correctly (with precision_digits)
  rma/models/stock_move.py
  rma/models/stock_picking.py
Labels: approved, bot is merging ⏳

#402 [16.0][FIX] rma: Add location_id field for the expected behavior
  rma/tests/test_rma.py
  rma/wizard/stock_picking_return_views.xml
Labels: approved, bot is merging ⏳
