Repository OCA/rma, pull requests merged in 2024-10, with the labels that each got.

#427 [16.0][ADD] rma_procurement_customer
  rma_procurement_customer/README.rst
  rma_procurement_customer/__init__.py
  rma_procurement_customer/__manifest__.py
  rma_procurement_customer/models/__init__.py
  rma_procurement_customer/models/rma.py
  rma_procurement_customer/readme/CONTRIBUTORS.md
  rma_procurement_customer/readme/DESCRIPTION.md
  rma_procurement_customer/static/description/icon.png
  rma_procurement_customer/static/description/index.html
  rma_procurement_customer/tests/__init__.py
  rma_procurement_customer/tests/test_rma_procurement_customer.py
  rma_procurement_customer/wizards/__init__.py
  rma_procurement_customer/wizards/stock_return_picking.py
  setup/rma_procurement_customer/odoo/addons/rma_procurement_customer
  setup/rma_procurement_customer/setup.py
Labels: needs review, approved, bot is merging ⏳

#428 [16.0][IMP] rma: dedicated settings section
  rma/views/res_config_settings_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#430 [16.0][IMP] rma: add product to rma search view
  rma/views/rma_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#419 [16.0][ADD] add rma_lot
  rma_lot/README.rst
  rma_lot/__init__.py
  rma_lot/__manifest__.py
  rma_lot/models/__init__.py
  rma_lot/models/rma.py
  rma_lot/readme/CONTRIBUTORS.md
  rma_lot/readme/DESCRIPTION.md
  rma_lot/static/description/icon.png
  rma_lot/static/description/index.html
  rma_lot/tests/__init__.py
  rma_lot/tests/test_rma_lot.py
  rma_lot/views/rma.xml
  rma_lot/wizards/__init__.py
  rma_lot/wizards/stock_return_picking_line.py
  rma_sale_lot/README.rst
  rma_sale_lot/__init__.py
  rma_sale_lot/__manifest__.py
  rma_sale_lot/models/__init__.py
  rma_sale_lot/models/sale_order.py
  rma_sale_lot/models/sale_order_line.py
  rma_sale_lot/readme/CONTRIBUTORS.md
  rma_sale_lot/readme/DESCRIPTION.md
  rma_sale_lot/static/description/icon.png
  rma_sale_lot/static/description/index.html
  rma_sale_lot/tests/__init__.py
  rma_sale_lot/tests/test_rma_sale_lot.py
  rma_sale_lot/wizards/__init__.py
  rma_sale_lot/wizards/sale_order_line_rma_wizard.py
  rma_sale_lot/wizards/sale_order_rma_wizard.xml
  setup/rma_lot/odoo/addons/rma_lot
  setup/rma_lot/setup.py
  setup/rma_sale_lot/odoo/addons/rma_sale_lot
  setup/rma_sale_lot/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#431 [17.0][MIG] rma_lot: Migration to 17.0
  rma_lot/README.rst
  rma_lot/__init__.py
  rma_lot/__manifest__.py
  rma_lot/i18n/rma_lot.pot
  rma_lot/models/__init__.py
  rma_lot/models/rma.py
  rma_lot/pyproject.toml
  rma_lot/readme/CONTRIBUTORS.md
  rma_lot/readme/DESCRIPTION.md
  rma_lot/static/description/icon.png
  rma_lot/static/description/index.html
  rma_lot/tests/__init__.py
  rma_lot/tests/test_rma_lot.py
  rma_lot/views/rma.xml
  rma_lot/wizards/__init__.py
  rma_lot/wizards/stock_return_picking_line.py
Labels: needs review, approved, migration, bot is merging ⏳
