Repository OCA/rma, pull requests merged in 2025-02, with the labels that each got.

#438 [17.0] [FIX] rma: fix for default_res_id as it is deprecated
  rma/models/rma.py
Labels: enhancement, needs review, approved, bot is merging ⏳

#445 [17.0][FIX] rma: Add Markup to messages to display the html code correctly + remaining_qty_to_done field
  rma/models/rma.py
Labels: approved, bot is merging ⏳

#446 [17.0][IMP] rma: improve rma report layout
  rma/views/report_rma.xml
Labels: bot is merging ⏳

#448 [16.0][FIX] rma: Allow to download the PDF of the picking from the RMA page
  rma/controllers/main.py
Labels: approved, bot is merging ⏳

#449 [17.0][FIX] rma: Allow to download the PDF of the picking from the RMA page
  rma/controllers/main.py
Labels: approved, bot is merging ⏳

#453 [16.0][FIX] rma_sale: Prevent the close icon from being displayed 2 times
  rma_sale/views/sale_portal_template.xml
Labels: approved, bot is merging ⏳

#452 [17.0][MIG] rma_sale: Migration to 17.0
  rma_sale/README.rst
  rma_sale/__init__.py
  rma_sale/__manifest__.py
  rma_sale/controllers/__init__.py
  rma_sale/controllers/rma_portal.py
  rma_sale/controllers/sale_portal.py
  rma_sale/i18n/de.po
  rma_sale/i18n/es.po
  rma_sale/i18n/fr.po
  rma_sale/i18n/it.po
  rma_sale/i18n/nl.po
  rma_sale/i18n/pt.po
  rma_sale/i18n/pt_BR.po
  rma_sale/i18n/rma_sale.pot
  rma_sale/i18n/ro.po
  rma_sale/models/__init__.py
  rma_sale/models/account_move.py
  rma_sale/models/res_company.py
  rma_sale/models/res_config_settings.py
  rma_sale/models/rma.py
  rma_sale/models/sale.py
  rma_sale/pyproject.toml
  rma_sale/readme/CONTRIBUTORS.md
  rma_sale/readme/DESCRIPTION.md
  rma_sale/readme/ROADMAP.md
  rma_sale/readme/USAGE.md
  rma_sale/security/ir.model.access.csv
  rma_sale/static/description/icon.png
  rma_sale/static/description/index.html
  rma_sale/static/src/js/rma_portal_form.esm.js
  rma_sale/static/src/scss/rma_sale.scss
  rma_sale/static/src/tests/test_rma_sale_portal_tour.esm.js
  rma_sale/tests/__init__.py
  rma_sale/tests/test_rma_sale.py
  rma_sale/tests/test_rma_sale_portal.py
  rma_sale/views/account_move_views.xml
  rma_sale/views/report_rma.xml
  rma_sale/views/res_config_settings_views.xml
  rma_sale/views/rma_views.xml
  rma_sale/views/sale_portal_template.xml
  rma_sale/views/sale_views.xml
  rma_sale/wizard/__init__.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
  rma_sale/wizard/stock_picking_return.py
Labels: needs review, approved, migration, bot is merging ⏳
