Repository OCA/rma, pull requests merged in 2025-06, with the labels that each got.

#424 [16.0][MIG] rma_delivery
  rma_delivery/README.rst
  rma_delivery/__init__.py
  rma_delivery/__manifest__.py
  rma_delivery/i18n/rma_delivery.pot
  rma_delivery/models/__init__.py
  rma_delivery/models/res_company.py
  rma_delivery/models/res_config_settings.py
  rma_delivery/models/rma.py
  rma_delivery/readme/CONFIGURE.rst
  rma_delivery/readme/CONTRIBUTORS.rst
  rma_delivery/readme/DESCRIPTION.rst
  rma_delivery/readme/USAGE.rst
  rma_delivery/static/description/icon.png
  rma_delivery/static/description/index.html
  rma_delivery/tests/__init__.py
  rma_delivery/tests/test_rma_delivery.py
  rma_delivery/views/res_config_settings_views.xml
  setup/rma_delivery/odoo/addons/rma_delivery
  setup/rma_delivery/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, no stale

#429 [16.0][IMP] rma: add dashboard
  rma/__manifest__.py
  rma/models/rma_operation.py
  rma/tests/__init__.py
  rma/tests/test_rma_dashboard.py
  rma/views/dashboard.xml
  rma/views/rma_views.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#407 [16.0][IMP] rma_sale: Display the allowed quantity to return in the RMA wizard
  rma_sale/README.rst
  rma_sale/controllers/sale_portal.py
  rma_sale/models/sale.py
  rma_sale/readme/CONTRIBUTORS.rst
  rma_sale/static/description/index.html
  rma_sale/tests/__init__.py
  rma_sale/tests/test_rma_sale.py
  rma_sale/tests/test_rma_sale_allowed_qty.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
  rma_sale_mrp/tests/test_rma_sale_mrp.py
  rma_sale_reason/tests/test_rma_sale_reason.py
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳, no stale

#417 [IMP] rma: configurable workflow
  rma/__manifest__.py
  rma/models/rma.py
  rma/models/rma_operation.py
  rma/static/description/index.html
  rma/tests/__init__.py
  rma/tests/test_rma_operation.py
  rma/views/rma_operation.xml
  rma/views/rma_views.xml
  rma/wizard/stock_picking_return.py
  rma/wizard/stock_picking_return_views.xml
  rma_sale/models/rma.py
  rma_sale/tests/test_rma_sale.py
  rma_sale/wizard/sale_order_rma_wizard.py
  rma_sale/wizard/sale_order_rma_wizard_views.xml
Labels: enhancement, needs review, approved, ready to merge, bot is merging ⏳

#433 [17.0][ADD] rma_repair: New module rma_repair
  rma_repair/README.rst
  rma_repair/__init__.py
  rma_repair/__manifest__.py
  rma_repair/i18n/ca.po
  rma_repair/i18n/es.po
  rma_repair/models/__init__.py
  rma_repair/models/repair.py
  rma_repair/models/rma.py
  rma_repair/pyproject.toml
  rma_repair/readme/CONTRIBUTORS.md
  rma_repair/readme/DESCRIPTION.md
  rma_repair/readme/USAGE.md
  rma_repair/static/description/icon.png
  rma_repair/static/description/icon.svg
  rma_repair/static/description/index.html
  rma_repair/tests/__init__.py
  rma_repair/tests/test_rma_repair_order.py
  rma_repair/views/repair_views.xml
  rma_repair/views/rma_views.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳
